version: '3.1'
services:
  database:
    container_name: api_database
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - "8081:8080"

volumes:
  data: