version: '3.1'
services:
  database:
    container_name: database
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
    - "8081:8080"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - database
    ports:
      - "8080:8080"

networks:
  app-network:
volumes:
  data: